apiVersion: v1
kind: ConfigMap
metadata:
  name: he4cloud-server-provisioning-config
data:
# Server Specific Environment Variables
  CLUSTER_IP: {{ .Values.env.cluster_ip | quote }}
  THREAD_POOL_SIZE: {{ .Values.env.thread_pool_size | quote }}
  API_VERSION: {{ .Values.env.api_version | quote }}
  LIMITATIONS: {{ .Values.env.limitations | toJson | quote }}
  EXPIRATION_FILE_PREFIX: {{ .Values.env.expiration_file_prefix | quote }}
  SHARED_MODELS_BUCKET: {{ .Values.env.shared_model_bucket | quote }}
  UPLOAD_LINK_TIMEOUT: {{ .Values.env.upload_link_timeout | quote }}
  LOCK_FILE: {{ .Values.env.lockFile | quote }}
# Common Library Environment Variables
  HE4C_ENV: {{ .Values.deployment.env }}
  LOGS_PATH: {{ .Values.env.logPath | quote }}
  LOGGER_STDOUT_LEVEL: {{ get .Values.logger.level.stdout .Values.deployment.stage | quote  }}
  LOGGER_FILE_LEVEL: {{ get .Values.logger.level.file .Values.deployment.stage | quote }}
  {{- if eq .Values.deployment.env "IBM" }}
  IBM_CLOUD_COS_ENDPOINT: {{ .Values.env.ibm.cos_endpoint | quote }}
  IBM_CLOUD_COS_INSTANCE_ID: {{ .Values.env.ibm.cos_instance_id | quote }}
  IBM_CLOUD_COS_IAM_AUTH_ENDPOINT: {{ .Values.env.ibm.cos_iam_auth_endpoint | quote }}
  IBM_CLOUD_COS_ACCESS_KEY_ID: {{ .Values.env.ibm.cos_access_key_id | quote }}
  IBM_CLOUD_APPID_AUTH_URL: {{ .Values.env.ibm.appid_auth_url | quote }}
  IBM_CLOUD_APPID_CLIENT_ID: {{ .Values.env.ibm.appid_client_id | quote }}
  CLOUDANT_URL: {{ .Values.env.ibm.cloudant_url | quote }}
  {{- end }}
  {{- if eq .Values.deployment.env "AWS" }}
  AWS_COGNITO_CLIENT_ID: {{ .Values.env.aws.cognito_client_id | quote }}
  AWS_COGNITO_IDENTITY_PROVIDER_NAME: {{ .Values.env.aws.cognito_identity_provider_name | quote }}
  AWS_COGNITO_SIGNING_KEYS_URL: {{ .Values.env.aws.cognito_signing_keys_url | quote }}
  MONGODB_DATABASE: {{ .Values.env.aws.mongodb_database | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.env.aws.access_key_id | quote }}
  {{- end }}
  {{- if eq .Values.deployment.env "K8S"}}
  KEYCLOAK_URL: {{ .Values.env.k8s.keycloak_url | quote }}
  KEYCLOAK_CLIENT_ID: {{ .Values.env.k8s.keycloak_client_id | quote }}
  MONGODB_DATABASE: {{ .Values.env.k8s.mongodb_database | quote }}
  MINIO_URL: {{ .Values.env.k8s.minio_url | quote }}
  MINIO_USER: {{ .Values.env.k8s.minio_user | quote }}
  {{- end }}
