site_name: IBM HElayers
site_url: https://ibm.github.io/helayers/
site_author: IBM FHE team
site_description: >-
  IBM HElayers homomorphic encryption SDK for C++ and Python

# Repository
#repo_name: IBM/helayers
#repo_url: https://github.com/IBM/helayers

nav:
  - Home: index.md
  - Python for x86: pylab.md
  - C++ for x86: lab.md
  - Python for Z: pylab-s390x.md
  - C++ for Z: lab-s390x.md
  - Documentation:
    - Python SDK: python-sdk/latest
    - C++ SDK: cpp-sdk/latest

# Copyright
#copyright: Copyright &copy; 2022 IBM

theme:
  name: material
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  features:
    - navigation.expand
