apiVersion: v1
kind: Service
metadata:
  name: {{ include "he4cloud-ui.fullname" . }}
  labels:
    {{- include "he4cloud-ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- toYaml .Values.service.ports | nindent 4 }}  
  selector:
    {{- include "he4cloud-ui.selectorLabels" . | nindent 4 }}
