apiVersion: v1
kind: Secret
metadata:
  name: he4cloud-server-provisioning-secret
type: Opaque
data:
  {{- if eq .Values.deployment.env "IBM" }}
  IBM_CLOUD_COS_IAM_API_KEY: {{ .Values.env.ibm.cos_iam_api_key | b64enc }}
  IBM_CLOUD_COS_SECRET_ACCESS_KEY: {{ .Values.env.ibm.cos_secret_access_key | b64enc }}
  IBM_CLOUD_APPID_CLIENT_SECRET: {{ .Values.env.ibm.appid_client_secret | b64enc }}
  CLOUDANT_APIKEY: {{ .Values.env.ibm.cloudant_apikey | b64enc }}
  {{- end }}
  {{- if eq .Values.deployment.env "AWS" }}
  MONGODB_CONNECTION_STRING: {{ .Values.env.aws.mongodb_connection_string | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.env.aws.secret_access_key | b64enc }}
  {{- end }}
  {{- if eq .Values.deployment.env "K8S" }}
  KEYCLOAK_CLIENT_SECRET: {{ .Values.env.k8s.keycloak_client_secret | b64enc }}
  MONGODB_CONNECTION_STRING: {{ .Values.env.k8s.mongodb_connection_string | b64enc }}
  MINIO_USER_PASSWORD: {{ .Values.env.k8s.minio_user_password | b64enc }}
  {{- end}}

